package view;

import javafx.scene.control.Alert;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import javafx.scene.image.ImageView;

/**
 * This class models the view of an alert box
 * when it is generated by the client
 */

public class AlertDialog extends Alert {	
	
	private final static String IMAGE_FOLDER = "/resources/";
	
	private final static String WARNING_IMAGE = "warning_icon.png";
	
	private final static String ERROR_IMAGE = "error_icon.png";
	
	/**
	 * Shows an alert box of type information to the user
	 *
	 * @param type the type of the alert box
	 * @param title the title shown in the alert box
	 * @param header the header shown in the alert box
	 * @param content the content shown in the alert box
	 * @param img the name of the image's file shown in the alert box
	 */
	
	public AlertDialog (Alert.AlertType type, String title, String header, String content, String img) {
		super(type);
		this.setTitle(title);
		this.setHeaderText(header);
		this.setContentText(content);
		Image image = new Image(getClass().getResourceAsStream(IMAGE_FOLDER + img));
		ImageView imageView = new ImageView(image);
		imageView.setFitWidth(64);
		imageView.setFitHeight(64);
		this.setGraphic(imageView);
		Stage stage = (Stage) this.getDialogPane().getScene().getWindow();
		stage.getIcons().add(image);
		this.showAndWait();
	}
	
	/**
	 * Shows an alert when the client generates an alert box
	 * of type warning, error or confirmation
	 *
	 * @param type the type of the alert box
	 * @param title the title shown in the alert box
	 * @param header the header shown in the alert box
	 * @param content the content shown in the alert box
	 */
	
	public AlertDialog (Alert.AlertType type, String title, String header, String content) {
		super(type);
		this.setTitle(title);
		this.setHeaderText(header);
		this.setContentText(content);
		Stage stage = (Stage) this.getDialogPane().getScene().getWindow();
		if(type == Alert.AlertType.WARNING) {
			stage.getIcons().add(new Image(getClass().getResourceAsStream(IMAGE_FOLDER + WARNING_IMAGE)));
			this.showAndWait();
		} else if(type == Alert.AlertType.ERROR) {
			stage.getIcons().add(new Image(getClass().getResourceAsStream(IMAGE_FOLDER + ERROR_IMAGE)));
			this.showAndWait();
		}else {
			stage.getIcons().add(new Image(getClass().getResourceAsStream(IMAGE_FOLDER + WARNING_IMAGE)));
		}
	}
}
