package controller;

import javafx.fxml.FXML;

import javafx.scene.layout.AnchorPane;
import javafx.scene.control.ComboBox;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;

import javafx.scene.shape.Circle;
import javafx.scene.paint.Color;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.beans.binding.BooleanBinding;
import javafx.beans.binding.Bindings;

import java.io.IOException;

import view.GearView;
import view.AlertDialog;
import view.DataVisualizationView;
import model.DataModel;

import java.util.Observer;
import java.util.Observable;

/**
 * This class manages some events generated by the graphic elements present in the "MainView" view
 */

public class MainController extends Controller implements Observer{
	@FXML
	private AnchorPane mainAnchorPane;
	
	@FXML
	private ComboBox<String> loadOptions;
	
	@FXML
	private AnchorPane leftPane;
	
	@FXML
	private AnchorPane rightPane;
	
	@FXML
	private ImageView gearIcon;
	
	@FXML
	private Circle statusCircle;
	
	@FXML
	private TextField tableName; 
	
	@FXML
	private TextField fileName;
	
	@FXML
	private TextField radius;
	
	@FXML
	private Button loadButton;
	
	@FXML
	private Button resetButton;

	@FXML
	/**
	 * Initialize the combobox and initialize the bindings for load button and reset button
	 */
	
	public void initialize() {
		loadOptions.setItems(FXCollections.observableArrayList(
				new String("Load From Database"),
				new String("Load From File")
				));
		loadOptions.getSelectionModel().select(0);
		rightPane.setDisable(true);
		
		BooleanBinding isStatusCircleRed = Bindings.equal(statusCircle.fillProperty(),Color.RED);
		BooleanBinding isTableNameFieldEmpty = Bindings.isEmpty(tableName.textProperty());
		BooleanBinding isRadiusFieldEmpty = Bindings.isEmpty(radius.textProperty());
		BooleanBinding isFileNameFieldEmpty = Bindings.isEmpty(fileName.textProperty());
		loadButton.disableProperty().bind(isStatusCircleRed.or(isFileNameFieldEmpty.and(isTableNameFieldEmpty.or(isRadiusFieldEmpty))));
		resetButton.disableProperty().bind(isFileNameFieldEmpty.and(isTableNameFieldEmpty.and(isRadiusFieldEmpty)));
		
	}

	/**
	 * Handler for the event generated by choosing one option of combobox (enable or disable file upload or dataset upload from db)
	 * @param event the event generated by choosing one option of combobox
	 */
	
	public void changeLoadOption(ActionEvent event) {
		if(loadOptions.getSelectionModel().getSelectedIndex() == 0) {
			//TO-DO ask the server for table names
			rightPane.setDisable(true);
			fileName.clear();
			leftPane.setDisable(false);
		} else {
			//TO-DO ask the server for file names
			rightPane.setDisable(false);
			tableName.clear();
			radius.clear();
			leftPane.setDisable(true);
		}
	}
	
	/**
	 * Handler for the event generated by the click of the "Gear" (create new window and ask for the connection parameters)
	 * @param event the event generated by Gear click 
	 */
	
	public void gearIconCliecked(MouseEvent event) {
		try {
			new GearView(this.model);
		}catch (IOException e){
			new AlertDialog(AlertType.WARNING,
					"ERROR",
					"ERROR OPENING A NEW WINDOW",
					"Unable to open a new option window. Try again...!"
					);
		}
	}
	
	/**
	 * This method is called whenever the observed object is changed. An application calls an 
	 * Observable object's notifyObservers method to have all the object's observers notified of the change
	 * @param obs the observable object
	 * @param obj an argument passed to the notifyObservers method
	 */
	
	public void update(Observable obs, Object obj) {
		DataModel m = (DataModel)obs;
		if(m.isConnected()) {
			statusCircle.setFill(Color.GREEN);
		}else {
			statusCircle.setFill(Color.RED);
		}
	}
	
	/**
	 * Handler for the event generated by the click of the "Load" button (open a new Window "DataVisualizzation")
	 * @param event the event generated by Load click 
	 */
	
	public void loadData(ActionEvent event) {
		try {
			if(loadOptions.getSelectionModel().getSelectedIndex() == 0) {
				model.setLoadDB(true);
				model.getDatabaseData().setDatabaseTable(tableName.getText());
				model.getDatabaseData().setRadius(Double.valueOf(radius.getText()));
				new DataVisualizationView(this.model);
			}else {
				model.setLoadDB(false);
				model.getFileData().setFileName(fileName.getText());
				new DataVisualizationView(this.model);
			}
		}catch (IOException e) {
			new AlertDialog(AlertType.ERROR,
					"FATAL ERROR",
					"ERROR LOADING FXML",
					"There are problems with loading the FXML file!"
					);
		}catch (NumberFormatException e) {
			new AlertDialog(AlertType.ERROR,
					"ERROR",
					"WRONG RADIUS FORM",
					"Insert numeric value for Radius!"
					);
			System.out.println("Error: " + e.getMessage());
		}
	}
	
	/**
	 * Handler for the event generated by the click of the "Reset" button
	 * @param event the event generated by Reset click 
	 */
	
	public void resetClicked(MouseEvent event) {
		if (rightPane.isDisable()) {
			tableName.clear();
			radius.clear();
		}else {
			fileName.clear();
		}
	}
	
}
