package controller;

import java.io.IOException;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.SocketException;

import javafx.beans.binding.Bindings;
import javafx.beans.binding.BooleanBinding;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import view.AlertDialog;
import javafx.scene.control.Alert.AlertType;
import model.DataModel;
import javafx.scene.input.MouseEvent;
import javafx.scene.control.ButtonType;
import java.util.Optional;

/**
 * This class manages some events generated by the graphic elements present in the "SaveView" view
 */

public class SaveController extends Controller{
	@FXML
	private Button saveButton;
	
	@FXML
	private Button resetButton;
	
	@FXML
	private TextField fileName;
	
	private ObjectInputStream input;
	private ObjectOutputStream output;

	/**
	 * Builds an object instance of SaveController and initialize the attributes
	 * Handles binds of buttons and textfields
	 * @param model the info of the client
	 * @param controlledStage references to the stage of the window
	 */
	
	public void init(DataModel model, Stage controlledStage) {
		super.init(model, controlledStage);
		input = model.getInputStream();
		output = model.getOutputStream();
		//Binding resetButton and saveButton
		BooleanBinding isfileNameEmpty = Bindings.isEmpty(fileName.textProperty());
		resetButton.disableProperty().bind(isfileNameEmpty);
		saveButton.disableProperty().bind(isfileNameEmpty);


	}
	
	/**
	 * Handler for the event generated by the click of the "Reset" button
	 * @param event the event generated by Reset click 
	 */
	
	public void resetClicked (MouseEvent e) {
		if (!fileName.getText().equals("")) {
			fileName.clear();
		}
	}
	
	/**
	 * Handler for the event generated by the click of the "Save" button (asks the user for the file name, if the server already has a file with this 
	 * name it asks whether to overwrite it or not)
	 * @param event the event generated by Save click 
	 */
	
	public void saveClicked (MouseEvent ev) {
		try {
			storeClustersInFile();
			
		}catch(SocketException e) {
			new AlertDialog(AlertType.ERROR,
					"ERROR",
					"CONNECTION ERROR",
					"Try to connect again to the server!"
					);
		}catch(ServerException e) {
			new AlertDialog(AlertType.ERROR,
					"ERROR",
					"SERVER ERROR",
					e.getMessage()
					);
		}catch (IOException | ClassNotFoundException e) {
			new AlertDialog(AlertType.ERROR,
					"ERROR",
					"COMMUNICATION ERROR",
					"An error occurred while communicating with the server!"
					);
		}
	}
	
	/**
	 * Send to server the name user specified, if the server already has a file with the name specified then, 
	 * it tells the client which will "ask" the user if he wants to overwrite it or not.
	 * The result will be communicated to the server
	 * @throws SocketException Thrown to indicate that there is an error creating or accessing a Socket.
	 * @throws IOException Signals that an I/O exception of some sort has occurred.
	 * @throws ClassNotFoundException Thrown when an application tries to load in a class through its string name
	 * @throws ServerException Thrown if there is something wrong with the communication with server
	 */
	
	private void storeClustersInFile() throws SocketException,ServerException,IOException,ClassNotFoundException{
		output.writeObject(2);
		output.writeObject(fileName.getText());
			if(((String)input.readObject()).equals("OK")) {
				new AlertDialog(AlertType.INFORMATION,
						"SAVING DIALOG",
						"ALL RIGHT !",
						"Saving Successful !",
						"successful_Icon.png"
						);
				String result = (String)input.readObject();
				if(!result.equals("OK"))
					 throw new ServerException(result);
			}else {
				AlertDialog a= new AlertDialog(AlertType.CONFIRMATION,
						"SAVING DIALOG",
						"WE'RE ALMOST DONE !",
						"Do you want to overwrite the file ?"
						);
				Optional<ButtonType> result = a.showAndWait();
				if (result.get() == ButtonType.OK){
					output.writeObject("Y");
					new AlertDialog(AlertType.INFORMATION,
							"SAVING DIALOG",
							"ALL RIGHT !",
							"Saving Successful !",
							"successful_Icon.png"
							);
					String results = (String)input.readObject();
					if(!results.equals("OK"))
						 throw new ServerException(results);
	            }else {
	            	output.writeObject("N");
	            }
			}
			
		//CHIUDO LA FINESTRA
		controlledStage.close();
	}
	
}